"""Synthetic industry datasets used by the demo loader. All names, numbers and locations are fictional.

Each spec describes a network and an item catalogue; demo_service turns it into consistent operational data.
Location tuple : (code, name, type, echelon, parent, region, city, lat, lon, capacity_units, demand_weight, extras)
Supplier tuple : (code, name, tier, country, city, lat, lon, geo_risk, reliability, lt_cv, weekly_capacity)
Item dict keys : sku, desc, fam, cat, cost, margin, weekly (total weekly demand across leaf nodes), pat (demand pattern),
                 src (BUY/MAKE), sup (supplier index), lt (static lead time days), moq, mult, shelf, crit, lot, plus extras.
"""

AUTOMOTIVE = {
    "code": "AUTOMOTIVE", "bu": "Powertrain", "profile": "AUTOMOTIVE",
    "suppliers": [
        ("AUT-S-PUNE", "Sahyadri Precision Castings", 1, "India", "Pune", 18.52, 73.86, 0.08, 0.93, 0.10, 40000),
        ("AUT-S-CHEN", "Coromandel Fasteners", 1, "India", "Chennai", 13.08, 80.27, 0.10, 0.88, 0.15, 90000),
        ("AUT-S-SHAN", "Huanjiang Electronics (Shanghai)", 2, "China", "Shanghai", 31.23, 121.47, 0.28, 0.80, 0.30, 60000),
        ("AUT-S-STUT", "Neckar Bearings GmbH", 2, "Germany", "Stuttgart", 48.78, 9.18, 0.12, 0.90, 0.18, 20000),
        ("AUT-S-NAGO", "Nagoya Sensor Works", 2, "Japan", "Nagoya", 35.18, 136.91, 0.14, 0.91, 0.16, 25000),
    ],
    "locations": [
        ("AUT-CDC-PUNE", "Pune Cross-Dock", "CDC", 1, None, "West", "Pune", 18.6, 73.8, 250000, 0.0, {}),
        ("AUT-PLT-CHK", "Chakan Assembly Plant", "PLANT", 2, "AUT-CDC-PUNE", "West", "Chakan", 18.76, 73.86, 120000, 0.0, {}),
        ("AUT-PLT-CHN", "Chennai Assembly Plant", "PLANT", 2, "AUT-CDC-PUNE", "South", "Chennai", 12.99, 80.2, 90000, 0.0, {}),
        ("AUT-LS-CHK1", "Chakan Line-Side A", "LINE_SIDE", 3, "AUT-PLT-CHK", "West", "Chakan", 18.76, 73.87, 15000, 0.55, {}),
        ("AUT-LS-CHN1", "Chennai Line-Side A", "LINE_SIDE", 3, "AUT-PLT-CHN", "South", "Chennai", 12.99, 80.21, 12000, 0.45, {}),
    ],
    "customers": [("AUT-C-OEM1", "Vahan Motors OEM", "OEM", 1, True, "West"), ("AUT-C-OEM2", "Sundaram Mobility", "OEM", 1, True, "South"),
                  ("AUT-C-AFT", "Aftermarket Distribution", "Aftermarket", 3, False, "West")],
    "items": [
        dict(sku="AUT-BRK-ACT-B", desc="Brake actuator (rev B)", fam="BRAKES", cat="Chassis", cost=2450, margin=0.28, weekly=520, pat="smooth", src="BUY", sup=0, lt=14, moq=200, mult=50, crit="Critical", lstop=18000, rev="B", superseded="AUT-BRK-ACT-C", eco_days=21, weight=1.4),
        dict(sku="AUT-BRK-ACT-C", desc="Brake actuator (rev C)", fam="BRAKES", cat="Chassis", cost=2520, margin=0.28, weekly=90, pat="trend_up", src="BUY", sup=0, lt=14, moq=200, mult=50, crit="Critical", lstop=18000, rev="C", weight=1.4),
        dict(sku="AUT-ECU-CTL", desc="Engine control unit", fam="ELECTRONICS", cat="Electrical", cost=7800, margin=0.30, weekly=380, pat="smooth", src="BUY", sup=2, lt=42, moq=300, mult=100, crit="Critical", lstop=45000, weight=0.6, mode="SEA", port="Nhava Sheva (JNPT)", lane="Shanghai→Nhava Sheva→Pune"),
        dict(sku="AUT-SNS-OXY", desc="Oxygen sensor", fam="ELECTRONICS", cat="Electrical", cost=1350, margin=0.32, weekly=610, pat="smooth", src="BUY", sup=4, lt=35, moq=500, mult=100, crit="High", lstop=9000, weight=0.2, mode="SEA", port="Chennai Port", lane="Nagoya→Chennai Port→Chennai"),
        dict(sku="AUT-BRG-6204", desc="Deep-groove bearing 6204", fam="BEARINGS", cat="Drivetrain", cost=310, margin=0.35, weekly=2400, pat="smooth", src="BUY", sup=3, lt=28, moq=2000, mult=500, crit="High", lstop=3000, weight=0.15, mode="SEA", port="Nhava Sheva (JNPT)", lane="Stuttgart→Nhava Sheva→Pune"),
        dict(sku="AUT-FST-M10", desc="Flange bolt M10x40", fam="FASTENERS", cat="Hardware", cost=9.5, margin=0.4, weekly=42000, pat="smooth", src="BUY", sup=1, lt=7, moq=20000, mult=5000, crit="Medium", weight=0.02),
        dict(sku="AUT-HSG-TRN", desc="Transmission housing casting", fam="CASTINGS", cat="Drivetrain", cost=4100, margin=0.26, weekly=340, pat="erratic", src="BUY", sup=0, lt=12, moq=100, mult=20, crit="High", lstop=22000, weight=11.0),
        dict(sku="AUT-GSK-HD", desc="Head gasket set", fam="SEALS", cat="Engine", cost=640, margin=0.38, weekly=780, pat="seasonal", src="BUY", sup=1, lt=9, moq=500, mult=100, crit="Medium", weight=0.3),
        dict(sku="AUT-WHS-ABS", desc="ABS wheel-speed harness", fam="ELECTRONICS", cat="Electrical", cost=880, margin=0.3, weekly=900, pat="smooth", src="BUY", sup=2, lt=38, moq=600, mult=100, crit="High", lstop=6000, weight=0.25, mode="SEA", port="Nhava Sheva (JNPT)", lane="Shanghai→Nhava Sheva→Pune"),
        dict(sku="AUT-CLT-KIT", desc="Clutch kit (legacy platform)", fam="DRIVETRAIN", cat="Drivetrain", cost=3900, margin=0.3, weekly=30, pat="declining", src="BUY", sup=0, lt=16, moq=50, mult=10, crit="Low", weight=6.0, life="EOL"),
        dict(sku="AUT-FG-TRN", desc="Transmission assembly (FG)", fam="ASSEMBLY", cat="Assembly", cost=38000, margin=0.22, weekly=260, pat="smooth", src="MAKE", sup=None, lt=6, moq=10, mult=1, crit="Critical", lstop=120000, weight=52.0, itype="FG"),
    ],
    "bom": [("AUT-FG-TRN", "AUT-BRG-6204", 4), ("AUT-FG-TRN", "AUT-HSG-TRN", 1), ("AUT-FG-TRN", "AUT-FST-M10", 32),
            ("AUT-FG-TRN", "AUT-BRK-ACT-B", 1), ("AUT-FG-TRN", "AUT-SNS-OXY", 2), ("AUT-FG-TRN", "AUT-GSK-HD", 2)],
    "repl": {"AUT-LS-CHK1": {"policy": "KANBAN", "container_qty": 200, "safety_days": 1}, "AUT-LS-CHN1": {"policy": "KANBAN", "container_qty": 200, "safety_days": 1},
             "AUT-PLT-CHK": {"policy": "MRP"}, "AUT-PLT-CHN": {"policy": "MRP"}, "AUT-CDC-PUNE": {"policy": "ROP"}},
    "sku_repl": {"AUT-BRG-6204": {"policy": "JIS", "sequence_days": 5}, "AUT-FST-M10": {"policy": "JIT", "window_days": 2}},
    "stock_cover": {"LINE_SIDE": 6, "PLANT": 14, "CDC": 22},
    "ship_days": 1,
}

FMCG = {
    "code": "FMCG", "bu": "Foods & Beverages", "profile": "RETAIL_FMCG",
    "suppliers": [
        ("FMC-S-PACK", "Deccan Flexi-Pack", 1, "India", "Pune", 18.5, 73.85, 0.07, 0.72, 0.30, 400000),
        ("FMC-S-SUGR", "Godavari Sugar Mills", 1, "India", "Kolhapur", 16.7, 74.24, 0.06, 0.95, 0.10, 900000),
        ("FMC-S-FLVR", "Aroma Flavours Ltd", 1, "India", "Mumbai", 19.08, 72.88, 0.06, 0.92, 0.12, 120000),
        ("FMC-S-COPK", "Sarita Co-Packers", 1, "India", "Baroda", 22.31, 73.19, 0.08, 0.89, 0.15, 300000),
    ],
    "locations": [
        ("FMC-PLT-01", "Nashik Food Plant", "PLANT", 1, None, "West", "Nashik", 19.99, 73.79, 900000, 0.0, {}),
        ("FMC-CDC-01", "Bhiwandi Central DC", "CDC", 2, "FMC-PLT-01", "West", "Bhiwandi", 19.3, 73.06, 700000, 0.0, {}),
        ("FMC-RDC-N", "Delhi North RDC", "RDC", 3, "FMC-CDC-01", "North", "Delhi", 28.61, 77.21, 260000, 0.34, {}),
        ("FMC-RDC-W", "Ahmedabad West RDC", "RDC", 3, "FMC-CDC-01", "West", "Ahmedabad", 23.02, 72.57, 220000, 0.33, {}),
        ("FMC-RDC-S", "Chennai South RDC", "RDC", 3, "FMC-CDC-01", "South", "Chennai", 13.08, 80.27, 240000, 0.33, {}),
    ],
    "customers": [("FMC-C-MT1", "BigBasket-style Modern Trade", "Modern Trade", 1, True, "South"), ("FMC-C-MT2", "MegaMart Hypermarkets", "Modern Trade", 1, True, "North"),
                  ("FMC-C-DIST", "Regional Distributors", "General Trade", 3, False, "West"), ("FMC-C-ECOM", "QuickShop E-commerce", "E-commerce", 2, False, "West")],
    "items": [
        dict(sku="FMC-BEV-COLA-1L", desc="Cola 1L PET", fam="BEVERAGES", cat="Carbonated", cost=24, margin=0.32, weekly=52000, pat="seasonal", src="MAKE", sup=None, lt=5, moq=20000, mult=2400, shelf=180, crit="Medium", lot=True, weight=1.1, itype="FG", promo=True),
        dict(sku="FMC-BEV-JUICE-200", desc="Mango juice 200ml", fam="BEVERAGES", cat="Juices", cost=9, margin=0.30, weekly=88000, pat="seasonal", src="MAKE", sup=None, lt=5, moq=48000, mult=4800, shelf=150, crit="Medium", lot=True, weight=0.22, itype="FG"),
        dict(sku="FMC-SNK-CHIP-50", desc="Potato chips 50g", fam="SNACKS", cat="Chips", cost=8.5, margin=0.34, weekly=120000, pat="smooth", src="MAKE", sup=None, lt=4, moq=60000, mult=6000, shelf=120, crit="Medium", lot=True, weight=0.06, itype="FG", promo=True),
        dict(sku="FMC-SNK-NOODLE", desc="Instant noodles 70g", fam="SNACKS", cat="Noodles", cost=11, margin=0.29, weekly=95000, pat="erratic", src="MAKE", sup=None, lt=4, moq=48000, mult=4800, shelf=270, crit="Medium", lot=True, weight=0.08, itype="FG"),
        dict(sku="FMC-PC-SOAP-100", desc="Bath soap 100g", fam="PERSONAL CARE", cat="Soap", cost=17, margin=0.36, weekly=64000, pat="smooth", src="MAKE", sup=None, lt=6, moq=30000, mult=3000, shelf=720, crit="Low", lot=True, weight=0.11, itype="FG"),
        dict(sku="FMC-PC-SHMP-180", desc="Shampoo 180ml", fam="PERSONAL CARE", cat="Hair care", cost=58, margin=0.4, weekly=30000, pat="smooth", src="MAKE", sup=None, lt=7, moq=12000, mult=1200, shelf=540, crit="Low", lot=True, weight=0.21, itype="FG"),
        dict(sku="FMC-DRY-BISC", desc="Cream biscuits 120g", fam="BAKERY", cat="Biscuits", cost=13, margin=0.3, weekly=70000, pat="trend_up", src="MAKE", sup=None, lt=5, moq=36000, mult=3600, shelf=210, crit="Medium", lot=True, weight=0.13, itype="FG"),
        dict(sku="FMC-RM-SUGAR", desc="Refined sugar (RM)", fam="RAW MATERIAL", cat="Ingredient", cost=41, margin=0.0, weekly=180000, pat="smooth", src="BUY", sup=1, lt=6, moq=50000, mult=5000, shelf=540, crit="High", lot=True, weight=1.0, itype="RAW", nofg=True),
        dict(sku="FMC-RM-FLAV", desc="Natural flavour concentrate", fam="RAW MATERIAL", cat="Ingredient", cost=1650, margin=0.0, weekly=2400, pat="smooth", src="BUY", sup=2, lt=15, moq=500, mult=50, shelf=365, crit="High", lot=True, weight=1.0, itype="RAW", nofg=True),
        dict(sku="FMC-PK-PET1L", desc="PET bottle 1L (packaging)", fam="PACKAGING", cat="Packaging", cost=6.2, margin=0.0, weekly=58000, pat="seasonal", src="BUY", sup=0, lt=10, moq=100000, mult=10000, crit="High", weight=0.03, itype="PACKAGING", nofg=True),
        dict(sku="FMC-PK-FILM", desc="Laminated snack film roll", fam="PACKAGING", cat="Packaging", cost=520, margin=0.0, weekly=900, pat="smooth", src="BUY", sup=0, lt=12, moq=200, mult=20, crit="High", weight=15.0, itype="PACKAGING", nofg=True),
    ],
    "bom": [("FMC-BEV-COLA-1L", "FMC-RM-SUGAR", 0.11), ("FMC-BEV-COLA-1L", "FMC-PK-PET1L", 1), ("FMC-BEV-COLA-1L", "FMC-RM-FLAV", 0.0006),
            ("FMC-SNK-CHIP-50", "FMC-PK-FILM", 0.0004)],
    "repl": {"FMC-RDC-N": {"policy": "DRP"}, "FMC-RDC-W": {"policy": "DRP"}, "FMC-RDC-S": {"policy": "DRP"}, "FMC-CDC-01": {"policy": "PERIODIC", "review_days": 7},
             "FMC-PLT-01": {"policy": "MRP"}},
    "sku_repl": {},
    "stock_cover": {"RDC": 16, "CDC": 24, "PLANT": 20},
    "ship_days": 2,
}

PHARMA = {
    "code": "PHARMA", "bu": "Formulations", "profile": "PHARMA",
    "suppliers": [
        ("PHM-S-API1", "Hyderabad API Labs", 1, "India", "Hyderabad", 17.38, 78.48, 0.09, 0.90, 0.14, 8000),
        ("PHM-S-EXCP", "Vapi Excipients", 1, "India", "Vapi", 20.37, 72.9, 0.08, 0.94, 0.10, 40000),
        ("PHM-S-PACK", "Cold-Pak Solutions", 1, "India", "Ahmedabad", 23.02, 72.57, 0.07, 0.86, 0.20, 30000),
        ("PHM-S-BIOL", "Rhein Biologics AG", 2, "Germany", "Frankfurt", 50.11, 8.68, 0.11, 0.87, 0.22, 3000),
    ],
    "locations": [
        ("PHM-PLT-01", "Baddi Formulation Plant", "PLANT", 1, None, "North", "Baddi", 30.96, 76.79, 60000, 0.0, {"temp": "CONTROLLED"}),
        ("PHM-CDC-01", "Hyderabad Central DC (GDP)", "CDC", 2, "PHM-PLT-01", "South", "Hyderabad", 17.4, 78.4, 90000, 0.0, {"temp": "CHILLED"}),
        ("PHM-RDC-E", "Kolkata East Depot", "RDC", 3, "PHM-CDC-01", "East", "Kolkata", 22.57, 88.36, 30000, 0.30, {"temp": "CHILLED"}),
        ("PHM-RDC-W", "Mumbai West Depot", "RDC", 3, "PHM-CDC-01", "West", "Mumbai", 19.08, 72.88, 42000, 0.40, {"temp": "CHILLED"}),
        ("PHM-3PL-N", "Delhi 3PL Cold Store", "3PL", 3, "PHM-CDC-01", "North", "Delhi", 28.61, 77.21, 26000, 0.30, {"temp": "CHILLED", "is3pl": True}),
    ],
    "customers": [("PHM-C-HOSP1", "Apex Hospitals Group", "Hospital", 1, True, "South"), ("PHM-C-DIST1", "MediDistribute India", "Distributor", 2, False, "West"),
                  ("PHM-C-GOV", "State Health Procurement", "Government", 1, True, "East"), ("PHM-C-RET", "PharmaPlus Chain", "Retail Pharmacy", 3, False, "North")],
    "items": [
        dict(sku="PHM-TAB-METF500", desc="Metformin 500mg tablets (blister)", fam="ORAL SOLID", cat="Antidiabetic", cost=42, margin=0.42, weekly=26000, pat="smooth", src="MAKE", sup=None, lt=12, moq=20000, mult=5000, shelf=730, crit="High", lot=True, weight=0.05, itype="FG", temp="AMBIENT"),
        dict(sku="PHM-TAB-ATOR20", desc="Atorvastatin 20mg tablets", fam="ORAL SOLID", cat="Cardiac", cost=68, margin=0.45, weekly=19000, pat="smooth", src="MAKE", sup=None, lt=12, moq=15000, mult=5000, shelf=730, crit="High", lot=True, weight=0.05, itype="FG", temp="AMBIENT"),
        dict(sku="PHM-INJ-INSUL", desc="Insulin glargine pen (cold chain)", fam="BIOLOGICS", cat="Antidiabetic", cost=690, margin=0.38, weekly=4200, pat="smooth", src="BUY", sup=3, lt=35, moq=2000, mult=500, shelf=540, crit="Critical", lot=True, weight=0.06, itype="FG", temp="CHILLED", lstop=5000),
        dict(sku="PHM-INJ-VACC", desc="Seasonal flu vaccine vial", fam="VACCINES", cat="Vaccines", cost=310, margin=0.4, weekly=3100, pat="seasonal", src="BUY", sup=3, lt=28, moq=1000, mult=200, shelf=270, crit="Critical", lot=True, weight=0.04, itype="FG", temp="CHILLED"),
        dict(sku="PHM-SYR-AMOX", desc="Amoxicillin syrup 60ml", fam="LIQUIDS", cat="Antibiotic", cost=56, margin=0.4, weekly=9500, pat="erratic", src="MAKE", sup=None, lt=10, moq=8000, mult=2000, shelf=365, crit="High", lot=True, weight=0.09, itype="FG", temp="AMBIENT"),
        dict(sku="PHM-CAP-OMEP20", desc="Omeprazole 20mg capsules", fam="ORAL SOLID", cat="Gastro", cost=35, margin=0.44, weekly=22000, pat="trend_up", src="MAKE", sup=None, lt=10, moq=15000, mult=5000, shelf=730, crit="Medium", lot=True, weight=0.04, itype="FG", temp="AMBIENT"),
        dict(sku="PHM-API-METF", desc="Metformin HCl API (kg)", fam="API", cat="API", cost=980, margin=0.0, weekly=1500, pat="smooth", src="BUY", sup=0, lt=21, moq=1000, mult=100, shelf=1095, crit="High", lot=True, weight=1.0, itype="RAW", temp="AMBIENT", nofg=True),
        dict(sku="PHM-EXC-MCC", desc="Microcrystalline cellulose (kg)", fam="EXCIPIENT", cat="Excipient", cost=210, margin=0.0, weekly=3200, pat="smooth", src="BUY", sup=1, lt=9, moq=2000, mult=250, shelf=1460, crit="Medium", lot=True, weight=1.0, itype="RAW", temp="AMBIENT", nofg=True),
        dict(sku="PHM-PK-BLIS", desc="Alu-alu blister foil (kg)", fam="PACKAGING", cat="Packaging", cost=890, margin=0.0, weekly=900, pat="smooth", src="BUY", sup=2, lt=14, moq=500, mult=50, shelf=None, crit="High", lot=False, weight=1.0, itype="PACKAGING", nofg=True),
        dict(sku="PHM-TAB-LEGACY", desc="Ranitidine 150mg (withdrawn brand)", fam="ORAL SOLID", cat="Gastro", cost=22, margin=0.3, weekly=0, pat="dead", src="MAKE", sup=None, lt=12, moq=10000, mult=5000, shelf=730, crit="Low", lot=True, weight=0.05, itype="FG", temp="AMBIENT", life="OBSOLETE"),
    ],
    "bom": [("PHM-TAB-METF500", "PHM-API-METF", 0.0005), ("PHM-TAB-METF500", "PHM-EXC-MCC", 0.0004), ("PHM-TAB-METF500", "PHM-PK-BLIS", 0.00002)],
    "repl": {"PHM-RDC-E": {"policy": "DRP"}, "PHM-RDC-W": {"policy": "DRP"}, "PHM-3PL-N": {"policy": "MIN_MAX"}, "PHM-CDC-01": {"policy": "PERIODIC", "review_days": 7}, "PHM-PLT-01": {"policy": "MRP"}},
    "sku_repl": {},
    "stock_cover": {"RDC": 24, "3PL": 24, "CDC": 34, "PLANT": 28},
    "ship_days": 2,
}

RETAIL = {
    "code": "RETAIL", "bu": "Omnichannel Retail", "profile": "RETAIL_FMCG",
    "suppliers": [
        ("RET-S-APRL", "Tiruppur Knitwear Exports", 1, "India", "Tiruppur", 11.11, 77.34, 0.09, 0.90, 0.16, 80000),
        ("RET-S-HOME", "Jaipur Home Décor", 1, "India", "Jaipur", 26.91, 75.79, 0.07, 0.83, 0.24, 30000),
        ("RET-S-ACC", "Guangzhou Accessories Co.", 2, "China", "Guangzhou", 23.13, 113.26, 0.25, 0.78, 0.35, 60000),
    ],
    "locations": [
        ("RET-DC-C", "Bhiwandi Central DC", "CDC", 1, None, "West", "Bhiwandi", 19.3, 73.06, 300000, 0.0, {}),
        ("RET-DC-S", "Bengaluru South DC", "RDC", 2, "RET-DC-C", "South", "Bengaluru", 12.97, 77.59, 60000, 0.0, {"tight": True}),
        ("RET-DC-N", "Gurugram North DC", "RDC", 2, "RET-DC-C", "North", "Gurugram", 28.46, 77.03, 120000, 0.0, {}),
        ("RET-ST-MUM", "Mumbai Flagship Store", "STORE", 3, "RET-DC-C", "West", "Mumbai", 19.07, 72.87, 6000, 0.24, {"channel": "STORE"}),
        ("RET-ST-BLR", "Bengaluru Mall Store", "STORE", 3, "RET-DC-S", "South", "Bengaluru", 12.93, 77.62, 4500, 0.20, {"channel": "STORE"}),
        ("RET-ST-DEL", "Delhi Select Store", "STORE", 3, "RET-DC-N", "North", "Delhi", 28.63, 77.22, 5200, 0.22, {"channel": "STORE"}),
        ("RET-DS-BLR", "Bengaluru Dark Store", "DARK_STORE", 3, "RET-DC-S", "South", "Bengaluru", 12.98, 77.6, 3500, 0.14, {"channel": "ONLINE"}),
        ("RET-MFC-MUM", "Mumbai Micro-Fulfilment Centre", "MFC", 3, "RET-DC-C", "West", "Mumbai", 19.1, 72.9, 4000, 0.20, {"channel": "ONLINE", "is3pl": True}),
    ],
    "customers": [("RET-C-WEB", "Web / App Shoppers", "Consumer", 3, False, "West"), ("RET-C-B2B", "Corporate Gifting B2B", "B2B", 2, True, "West")],
    "items": [
        dict(sku="RET-APP-TEE-M", desc="Cotton crew tee - M", fam="APPAREL", cat="Tops", cost=190, margin=0.55, weekly=3800, pat="seasonal", src="BUY", sup=0, lt=25, moq=1500, mult=100, crit="Medium", weight=0.2, markdown=0.4, promo=True),
        dict(sku="RET-APP-JEAN-32", desc="Slim jeans - 32", fam="APPAREL", cat="Bottoms", cost=640, margin=0.5, weekly=2100, pat="smooth", src="BUY", sup=0, lt=30, moq=800, mult=50, crit="Medium", weight=0.6, markdown=0.35),
        dict(sku="RET-APP-JKT-WNT", desc="Winter jacket", fam="APPAREL", cat="Outerwear", cost=1450, margin=0.52, weekly=900, pat="seasonal_winter", src="BUY", sup=0, lt=35, moq=400, mult=25, crit="Low", weight=1.1, markdown=0.5, promo=True),
        dict(sku="RET-HOM-CUSH", desc="Printed cushion cover", fam="HOME", cat="Décor", cost=145, margin=0.6, weekly=1900, pat="erratic", src="BUY", sup=1, lt=20, moq=800, mult=100, crit="Low", weight=0.3, markdown=0.3),
        dict(sku="RET-HOM-LAMP", desc="Ceramic table lamp", fam="HOME", cat="Lighting", cost=780, margin=0.5, weekly=520, pat="intermittent", src="BUY", sup=1, lt=24, moq=200, mult=20, crit="Low", weight=2.4, markdown=0.3),
        dict(sku="RET-ACC-EARB", desc="Wireless earbuds", fam="ACCESSORIES", cat="Audio", cost=690, margin=0.4, weekly=2600, pat="spike", src="BUY", sup=2, lt=45, moq=1000, mult=100, crit="High", weight=0.15, mode="SEA", promo=True, port="Nhava Sheva (JNPT)", lane="Guangzhou→Nhava Sheva→Bhiwandi"),
        dict(sku="RET-ACC-PWRB", desc="Power bank 10000mAh", fam="ACCESSORIES", cat="Power", cost=520, margin=0.42, weekly=2200, pat="smooth", src="BUY", sup=2, lt=45, moq=1000, mult=100, crit="Medium", weight=0.3, mode="SEA", port="Nhava Sheva (JNPT)", lane="Guangzhou→Nhava Sheva→Bhiwandi"),
        dict(sku="RET-APP-SCARF", desc="Wool scarf (last season)", fam="APPAREL", cat="Accessories", cost=260, margin=0.5, weekly=160, pat="declining", src="BUY", sup=0, lt=25, moq=400, mult=50, crit="Low", weight=0.15, markdown=0.6),
        dict(sku="RET-HOM-TOWEL", desc="Bath towel set", fam="HOME", cat="Bath", cost=420, margin=0.48, weekly=1200, pat="smooth", src="BUY", sup=1, lt=18, moq=600, mult=50, crit="Low", weight=0.8, markdown=0.3),
        dict(sku="RET-APP-SOCK", desc="Ankle socks 3-pack", fam="APPAREL", cat="Basics", cost=95, margin=0.6, weekly=4500, pat="smooth", src="BUY", sup=0, lt=20, moq=3000, mult=300, crit="Low", weight=0.1, markdown=0.25),
    ],
    "bom": [],
    "repl": {"RET-ST-MUM": {"policy": "MIN_MAX"}, "RET-ST-BLR": {"policy": "MIN_MAX"}, "RET-ST-DEL": {"policy": "MIN_MAX"}, "RET-DS-BLR": {"policy": "MIN_MAX"},
             "RET-MFC-MUM": {"policy": "MIN_MAX"}, "RET-DC-S": {"policy": "DRP"}, "RET-DC-N": {"policy": "DRP"}, "RET-DC-C": {"policy": "PERIODIC", "review_days": 7}},
    "sku_repl": {},
    "stock_cover": {"STORE": 14, "DARK_STORE": 10, "MFC": 10, "RDC": 24, "CDC": 30},
    "ship_days": 2,
}

ELECTRONICS = {
    "code": "ELECTRONICS", "bu": "EMS / Consumer Electronics", "profile": "HIGH_TECH",
    "suppliers": [
        ("ELE-S-TWN", "Hsinchu Semiconductor", 1, "Taiwan", "Hsinchu", 24.8, 120.97, 0.30, 0.74, 0.40, 400000),
        ("ELE-S-SZX", "Shenzhen Passive Components", 1, "China", "Shenzhen", 22.54, 114.06, 0.24, 0.80, 0.30, 900000),
        ("ELE-S-KOR", "Seoul Memory Distribution", 2, "South Korea", "Seoul", 37.57, 126.98, 0.14, 0.85, 0.28, 300000),
        ("ELE-S-PCB", "Noida PCB Fabricators", 1, "India", "Noida", 28.54, 77.39, 0.08, 0.90, 0.15, 60000),
        ("ELE-S-CON", "Penang Connectors", 2, "Malaysia", "Penang", 5.41, 100.33, 0.16, 0.88, 0.22, 500000),
    ],
    "locations": [
        ("ELE-DC-01", "Chennai Import Hub", "CDC", 1, None, "South", "Chennai", 13.0, 80.2, 400000, 0.0, {}),
        ("ELE-PLT-01", "Sriperumbudur EMS Plant", "PLANT", 2, "ELE-DC-01", "South", "Sriperumbudur", 12.96, 79.94, 250000, 0.6, {}),
        ("ELE-PLT-02", "Noida EMS Plant", "PLANT", 2, "ELE-DC-01", "North", "Noida", 28.53, 77.39, 180000, 0.4, {}),
    ],
    "customers": [("ELE-C-OEM1", "Lumina Consumer Devices", "OEM", 1, True, "South"), ("ELE-C-OEM2", "Kavach Smart Meters", "OEM", 2, True, "North")],
    "items": [
        dict(sku="ELE-IC-MCU32", desc="32-bit MCU (QFP-64)", fam="ICS", cat="Semiconductor", cost=185, margin=0.25, weekly=14000, pat="smooth", src="BUY", sup=0, lt=84, moq=5000, mult=1000, crit="Critical", lstop=1200, alt="MCU-32", mode="AIR", weight=0.002, lane="Hsinchu→Chennai (AIR)"),
        dict(sku="ELE-IC-MCU32B", desc="32-bit MCU alt. source (QFP-64)", fam="ICS", cat="Semiconductor", cost=205, margin=0.25, weekly=1500, pat="smooth", src="BUY", sup=2, lt=70, moq=5000, mult=1000, crit="High", alt="MCU-32", mode="AIR", weight=0.002, lane="Seoul→Chennai (AIR)"),
        dict(sku="ELE-IC-PMIC", desc="Power management IC", fam="ICS", cat="Semiconductor", cost=96, margin=0.28, weekly=21000, pat="erratic", src="BUY", sup=0, lt=98, moq=10000, mult=2500, crit="Critical", lstop=900, mode="AIR", weight=0.002, lane="Hsinchu→Chennai (AIR)"),
        dict(sku="ELE-CAP-100N", desc="MLCC 100nF 0402 (reel)", fam="PASSIVES", cat="Capacitor", cost=1.8, margin=0.3, weekly=1600000, pat="smooth", src="BUY", sup=1, lt=45, moq=500000, mult=50000, crit="Medium", weight=0.0001, mode="SEA", port="Chennai Port", lane="Shenzhen→Chennai Port→Chennai"),
        dict(sku="ELE-RES-10K", desc="Resistor 10k 0402 (reel)", fam="PASSIVES", cat="Resistor", cost=0.6, margin=0.3, weekly=2400000, pat="smooth", src="BUY", sup=1, lt=40, moq=1000000, mult=100000, crit="Low", weight=0.0001, mode="SEA", port="Chennai Port", lane="Shenzhen→Chennai Port→Chennai"),
        dict(sku="ELE-MEM-DDR4", desc="DDR4 memory 4GB", fam="MEMORY", cat="Memory", cost=1450, margin=0.18, weekly=5200, pat="erratic", src="BUY", sup=2, lt=60, moq=1000, mult=250, crit="High", lstop=2500, mode="AIR", weight=0.02, life="EOL", eol_days=120, lane="Seoul→Chennai (AIR)"),
        dict(sku="ELE-PCB-CTRL", desc="Controller PCB (6-layer)", fam="PCB", cat="Board", cost=310, margin=0.3, weekly=6500, pat="smooth", src="BUY", sup=3, lt=21, moq=2000, mult=250, crit="High", lstop=1800, weight=0.09),
        dict(sku="ELE-CON-USBC", desc="USB-C connector", fam="CONNECTORS", cat="Connector", cost=14, margin=0.3, weekly=48000, pat="trend_up", src="BUY", sup=4, lt=42, moq=20000, mult=5000, crit="Medium", mode="SEA", port="Chennai Port", weight=0.004, lane="Penang→Chennai Port→Chennai"),
        dict(sku="ELE-IC-OLD-PHY", desc="Ethernet PHY (last-time-buy lifecycle)", fam="ICS", cat="Semiconductor", cost=240, margin=0.2, weekly=900, pat="declining", src="BUY", sup=0, lt=90, moq=5000, mult=1000, crit="Medium", mode="AIR", weight=0.002, life="EOL", eol_days=45, lane="Hsinchu→Chennai (AIR)"),
        dict(sku="ELE-FG-CTRL", desc="Smart controller unit (FG)", fam="FINISHED", cat="Product", cost=2650, margin=0.22, weekly=3600, pat="smooth", src="MAKE", sup=None, lt=8, moq=500, mult=50, crit="High", lstop=8000, weight=0.4, itype="FG"),
    ],
    "bom": [("ELE-FG-CTRL", "ELE-IC-MCU32", 1), ("ELE-FG-CTRL", "ELE-IC-PMIC", 2), ("ELE-FG-CTRL", "ELE-CAP-100N", 22), ("ELE-FG-CTRL", "ELE-RES-10K", 35),
            ("ELE-FG-CTRL", "ELE-PCB-CTRL", 1), ("ELE-FG-CTRL", "ELE-CON-USBC", 2), ("ELE-FG-CTRL", "ELE-MEM-DDR4", 1)],
    "repl": {"ELE-PLT-01": {"policy": "MRP"}, "ELE-PLT-02": {"policy": "MRP"}, "ELE-DC-01": {"policy": "ROP"}},
    "sku_repl": {},
    "stock_cover": {"PLANT": 40, "CDC": 55},
    "ship_days": 2,
}

SPARE_PARTS = {
    "code": "SPARE_PARTS", "bu": "Aftermarket Service", "profile": "SPARE_PARTS",
    "suppliers": [
        ("SPR-S-OEM1", "Turbotech OEM Germany", 1, "Germany", "Munich", 48.14, 11.58, 0.12, 0.84, 0.30, 4000),
        ("SPR-S-OEM2", "Kobe Hydraulics", 1, "Japan", "Kobe", 34.69, 135.2, 0.14, 0.90, 0.20, 5000),
        ("SPR-S-LOC", "Rajkot Machined Parts", 1, "India", "Rajkot", 22.3, 70.8, 0.07, 0.92, 0.12, 12000),
    ],
    "locations": [
        ("SPR-CDC-01", "Nagpur Central Parts Depot", "CDC", 1, None, "Central", "Nagpur", 21.15, 79.09, 120000, 0.0, {}),
        ("SPR-RD-N", "North Regional Depot", "RDC", 2, "SPR-CDC-01", "North", "Ludhiana", 30.9, 75.85, 30000, 0.28, {}),
        ("SPR-RD-S", "South Regional Depot", "RDC", 2, "SPR-CDC-01", "South", "Hosur", 12.74, 77.83, 30000, 0.26, {}),
        ("SPR-RD-E", "East Regional Depot", "RDC", 2, "SPR-CDC-01", "East", "Kolkata", 22.57, 88.36, 26000, 0.22, {}),
        ("SPR-RD-W", "West Regional Depot", "RDC", 2, "SPR-CDC-01", "West", "Pune", 18.52, 73.86, 34000, 0.24, {}),
    ],
    "customers": [("SPR-C-FLEET", "Mining Fleet Services", "Service contract", 1, True, "Central"), ("SPR-C-DEAL", "Authorised Dealer Network", "Dealer", 2, False, "West"),
                  ("SPR-C-WALK", "Walk-in / Spot orders", "Spot", 4, False, "South")],
    "items": [
        dict(sku="SPR-HYD-PUMP", desc="Hydraulic main pump", fam="HYDRAULICS", cat="Pumps", cost=84000, margin=0.35, weekly=3.2, pat="intermittent", src="BUY", sup=1, lt=75, moq=1, mult=1, crit="Critical", lstop=650000, weight=48.0, serial=True, mode="SEA", port="Chennai Port", lane="Kobe→Chennai Port→Hosur"),
        dict(sku="SPR-TRB-BLADE", desc="Turbine blade set", fam="TURBINE", cat="Rotating", cost=126000, margin=0.33, weekly=0.9, pat="intermittent", src="BUY", sup=0, lt=112, moq=1, mult=1, crit="Critical", lstop=1400000, weight=85.0, serial=True, mode="AIR", lane="Munich→Nagpur (AIR)"),
        dict(sku="SPR-SEAL-KIT", desc="Shaft seal kit", fam="SEALS", cat="Consumable", cost=2200, margin=0.5, weekly=22, pat="lumpy", src="BUY", sup=2, lt=14, moq=10, mult=5, crit="High", lstop=25000, weight=0.4),
        dict(sku="SPR-FLT-OIL", desc="Oil filter cartridge", fam="FILTERS", cat="Consumable", cost=780, margin=0.45, weekly=140, pat="smooth", src="BUY", sup=2, lt=10, moq=50, mult=25, crit="Medium", weight=0.6),
        dict(sku="SPR-BRG-SPH", desc="Spherical roller bearing", fam="BEARINGS", cat="Rotating", cost=18500, margin=0.4, weekly=5.5, pat="intermittent", src="BUY", sup=0, lt=60, moq=2, mult=1, crit="High", lstop=180000, weight=9.0, mode="SEA", port="Nhava Sheva (JNPT)", lane="Munich→Nhava Sheva→Nagpur"),
        dict(sku="SPR-VLV-CTRL", desc="Control valve assembly", fam="HYDRAULICS", cat="Valves", cost=41000, margin=0.38, weekly=2.4, pat="lumpy", src="BUY", sup=1, lt=70, moq=1, mult=1, crit="Critical", lstop=520000, weight=15.0, mode="SEA", port="Chennai Port", lane="Kobe→Chennai Port→Hosur"),
        dict(sku="SPR-BLT-DRV", desc="Drive belt set", fam="DRIVE", cat="Consumable", cost=3400, margin=0.5, weekly=32, pat="smooth", src="BUY", sup=2, lt=12, moq=10, mult=2, crit="Medium", weight=1.2),
        dict(sku="SPR-PCB-OLD", desc="Legacy control board (machine retired)", fam="ELECTRONICS", cat="Controls", cost=52000, margin=0.4, weekly=0, pat="dead", src="BUY", sup=0, lt=90, moq=1, mult=1, crit="Low", weight=1.0, life="OBSOLETE", serial=True),
        dict(sku="SPR-GBX-REBUILT", desc="Gearbox rebuilt (exchange unit)", fam="GEARBOX", cat="Rotating", cost=210000, margin=0.3, weekly=0.4, pat="intermittent", src="BUY", sup=0, lt=105, moq=1, mult=1, crit="Critical", lstop=1900000, weight=310.0, serial=True, mode="SEA", port="Nhava Sheva (JNPT)", lane="Munich→Nhava Sheva→Nagpur"),
        dict(sku="SPR-GSK-FLNG", desc="Flange gasket (pack of 10)", fam="SEALS", cat="Consumable", cost=640, margin=0.55, weekly=60, pat="smooth", src="BUY", sup=2, lt=8, moq=20, mult=10, crit="Low", weight=0.3),
        dict(sku="SPR-MTR-SENS", desc="Motor temperature sensor", fam="ELECTRONICS", cat="Sensor", cost=5200, margin=0.42, weekly=9, pat="lumpy", src="BUY", sup=1, lt=40, moq=5, mult=1, crit="High", lstop=60000, weight=0.2, mode="SEA", lane="Kobe→Chennai Port→Hosur", port="Chennai Port"),
        dict(sku="SPR-OLD-COUPL", desc="Coupling (superseded design)", fam="DRIVE", cat="Rotating", cost=9800, margin=0.35, weekly=0, pat="dead", src="BUY", sup=2, lt=30, moq=1, mult=1, crit="Low", weight=6.0, life="OBSOLETE"),
    ],
    "bom": [],
    "repl": {"SPR-CDC-01": {"policy": "ROP"}, "SPR-RD-N": {"policy": "MIN_MAX"}, "SPR-RD-S": {"policy": "MIN_MAX"}, "SPR-RD-E": {"policy": "MIN_MAX"}, "SPR-RD-W": {"policy": "MIN_MAX"}},
    "sku_repl": {},
    "stock_cover": {"RDC": 90, "CDC": 150},
    "ship_days": 3,
}

MANUFACTURING = {
    "code": "MANUFACTURING", "bu": "Industrial Equipment", "profile": "MANUFACTURING",
    "suppliers": [
        ("MFG-S-STEL", "Jamshedpur Steel Traders", 1, "India", "Jamshedpur", 22.8, 86.2, 0.07, 0.91, 0.14, 1200000),
        ("MFG-S-CAST", "Coimbatore Foundry", 1, "India", "Coimbatore", 11.0, 76.96, 0.08, 0.85, 0.20, 90000),
        ("MFG-S-CHEM", "Dahej Industrial Chemicals", 1, "India", "Dahej", 21.7, 72.6, 0.09, 0.93, 0.10, 300000),
        ("MFG-S-MOTR", "Wuxi Motor Works", 2, "China", "Wuxi", 31.49, 120.31, 0.22, 0.82, 0.28, 8000),
    ],
    "locations": [
        ("MFG-WH-RM", "Raw Material Warehouse", "WAREHOUSE", 1, None, "West", "Aurangabad", 19.88, 75.34, 400000, 0.0, {}),
        ("MFG-PLT-01", "Aurangabad Plant (Shop-floor)", "PLANT", 2, "MFG-WH-RM", "West", "Aurangabad", 19.9, 75.35, 150000, 0.0, {}),
        ("MFG-WH-FG", "Finished Goods Warehouse", "WAREHOUSE", 3, "MFG-PLT-01", "West", "Aurangabad", 19.86, 75.32, 60000, 0.62, {}),
        ("MFG-DC-E", "Kolkata Distribution Centre", "RDC", 3, "MFG-PLT-01", "East", "Kolkata", 22.6, 88.4, 30000, 0.38, {}),
    ],
    "customers": [("MFG-C-EPC", "Infra EPC Contractors", "Project", 2, True, "West"), ("MFG-C-DEAL", "Industrial Dealers", "Dealer", 3, False, "East"),
                  ("MFG-C-EXP", "Export Customers", "Export", 2, False, "West")],
    "items": [
        dict(sku="MFG-RM-STEEL", desc="Cold-rolled steel coil (kg)", fam="RAW MATERIAL", cat="Steel", cost=68, margin=0.0, weekly=88000, pat="smooth", src="BUY", sup=0, lt=8, moq=25000, mult=5000, crit="High", weight=1.0, itype="RAW", nofg=True),
        dict(sku="MFG-RM-CAST", desc="Grey iron casting blank", fam="RAW MATERIAL", cat="Castings", cost=1850, margin=0.0, weekly=640, pat="erratic", src="BUY", sup=1, lt=21, moq=200, mult=20, crit="High", weight=22.0, itype="RAW", nofg=True),
        dict(sku="MFG-RM-PAINT", desc="Industrial epoxy paint (litre)", fam="RAW MATERIAL", cat="Chemicals", cost=390, margin=0.0, weekly=2600, pat="smooth", src="BUY", sup=2, lt=7, moq=1000, mult=100, shelf=365, crit="Medium", lot=True, weight=1.2, itype="RAW", hazmat=True, nofg=True),
        dict(sku="MFG-RM-MOTOR", desc="3-phase induction motor 15kW", fam="COMPONENT", cat="Motors", cost=32500, margin=0.0, weekly=95, pat="smooth", src="BUY", sup=3, lt=55, moq=40, mult=10, crit="Critical", lstop=140000, weight=120.0, itype="COMPONENT", mode="SEA", port="Nhava Sheva (JNPT)", lane="Wuxi→Nhava Sheva→Aurangabad", nofg=True),
        dict(sku="MFG-RM-BOLT", desc="HT bolt kit", fam="COMPONENT", cat="Hardware", cost=140, margin=0.0, weekly=9000, pat="smooth", src="BUY", sup=0, lt=6, moq=5000, mult=500, crit="Low", weight=0.25, itype="COMPONENT", nofg=True),
        dict(sku="MFG-WIP-FRAME", desc="Welded frame (WIP)", fam="WIP", cat="Subassembly", cost=9200, margin=0.0, weekly=380, pat="smooth", src="MAKE", sup=None, lt=3, moq=20, mult=5, crit="High", weight=80.0, itype="SEMI", nofg=True, wip=True),
        dict(sku="MFG-FG-PUMPSET", desc="Industrial pump set 15kW", fam="FINISHED", cat="Pumps", cost=71000, margin=0.28, weekly=88, pat="smooth", src="MAKE", sup=None, lt=7, moq=10, mult=1, crit="High", weight=210.0, itype="FG"),
        dict(sku="MFG-FG-COMPRSR", desc="Screw compressor 30kW", fam="FINISHED", cat="Compressors", cost=168000, margin=0.26, weekly=34, pat="seasonal", src="MAKE", sup=None, lt=9, moq=5, mult=1, crit="Medium", weight=420.0, itype="FG"),
        dict(sku="MFG-FG-GBOX", desc="Helical gearbox", fam="FINISHED", cat="Gearboxes", cost=48000, margin=0.3, weekly=52, pat="erratic", src="MAKE", sup=None, lt=8, moq=5, mult=1, crit="Medium", weight=160.0, itype="FG"),
    ],
    "bom": [("MFG-WIP-FRAME", "MFG-RM-STEEL", 60), ("MFG-WIP-FRAME", "MFG-RM-BOLT", 12),
            ("MFG-FG-PUMPSET", "MFG-WIP-FRAME", 1), ("MFG-FG-PUMPSET", "MFG-RM-MOTOR", 1), ("MFG-FG-PUMPSET", "MFG-RM-CAST", 2), ("MFG-FG-PUMPSET", "MFG-RM-PAINT", 4),
            ("MFG-FG-COMPRSR", "MFG-WIP-FRAME", 1), ("MFG-FG-COMPRSR", "MFG-RM-MOTOR", 1), ("MFG-FG-GBOX", "MFG-RM-CAST", 3)],
    "repl": {"MFG-WH-RM": {"policy": "ROP"}, "MFG-PLT-01": {"policy": "MRP"}, "MFG-WH-FG": {"policy": "MIN_MAX"}, "MFG-DC-E": {"policy": "DRP"}},
    "sku_repl": {},
    "stock_cover": {"WAREHOUSE": 24, "PLANT": 12, "RDC": 20},
    "ship_days": 2,
}

SPECS = {s["code"]: s for s in (AUTOMOTIVE, FMCG, PHARMA, RETAIL, ELECTRONICS, SPARE_PARTS, MANUFACTURING)}
INDUSTRY_LABELS = {"AUTOMOTIVE": "Automotive", "FMCG": "FMCG", "PHARMA": "Pharma", "RETAIL": "Retail (omnichannel)",
                   "ELECTRONICS": "Electronics / High-tech", "SPARE_PARTS": "Spare parts", "MANUFACTURING": "Manufacturing"}
