"""initial schema

Revision ID: 8caecae3931b
Revises: 
Create Date: 2026-09-22 02:44:31.630506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8caecae3931b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('actor', sa.String(length=60), nullable=True),
    sa.Column('category', sa.String(length=12), nullable=True),
    sa.Column('entity_type', sa.String(length=30), nullable=True),
    sa.Column('entity_id', sa.String(length=60), nullable=True),
    sa.Column('event', sa.String(length=80), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('trace', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_timestamp'), ['timestamp'], unique=False)

    op.create_table('autonomy_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('action_types', sa.JSON(), nullable=True),
    sa.Column('effect', sa.String(length=20), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carrier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('mode', sa.String(length=12), nullable=True),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('control_policy',
    sa.Column('policy_type', sa.String(length=24), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope_level', sa.String(length=14), nullable=False),
    sa.Column('scope_key', sa.String(length=120), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('control_policy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_control_policy_policy_type'), ['policy_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_control_policy_scope_level'), ['scope_level'], unique=False)

    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('segment', sa.String(length=40), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('contract_priority', sa.Boolean(), nullable=True),
    sa.Column('region', sa.String(length=60), nullable=True),
    sa.Column('country', sa.String(length=60), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('industry', sa.String(length=30), nullable=True),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_customer_region'), ['region'], unique=False)

    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=True),
    sa.Column('error', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_event_type'), ['event_type'], unique=False)

    op.create_table('experiment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exp_no', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=True),
    sa.Column('hypothesis', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=True),
    sa.Column('created_by', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exp_no')
    )
    op.create_table('external_balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system', sa.String(length=20), nullable=False),
    sa.Column('sku_raw', sa.String(length=60), nullable=False),
    sa.Column('location_raw', sa.String(length=40), nullable=False),
    sa.Column('lot_no', sa.String(length=60), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('uom', sa.String(length=12), nullable=True),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.Column('snapshot_at', sa.DateTime(), nullable=True),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('external_balance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_balance_system'), ['system'], unique=False)

    op.create_table('incident',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_no', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('root_cause', sa.String(length=255), nullable=True),
    sa.Column('cause_type', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('cluster_key', sa.String(length=160), nullable=True),
    sa.Column('dims', sa.JSON(), nullable=True),
    sa.Column('impact', sa.JSON(), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('owner', sa.String(length=60), nullable=True),
    sa.Column('explain', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_no')
    )
    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_cluster_key'), ['cluster_key'], unique=False)

    op.create_table('industry_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('terminology', sa.JSON(), nullable=True),
    sa.Column('kpis', sa.JSON(), nullable=True),
    sa.Column('rules', sa.JSON(), nullable=True),
    sa.Column('dashboards', sa.JSON(), nullable=True),
    sa.Column('alerts', sa.JSON(), nullable=True),
    sa.Column('policies', sa.JSON(), nullable=True),
    sa.Column('recommended_actions', sa.JSON(), nullable=True),
    sa.Column('focus', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('inventory_state_def',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=60), nullable=True),
    sa.Column('category', sa.String(length=12), nullable=True),
    sa.Column('counts_on_hand', sa.Boolean(), nullable=True),
    sa.Column('allocatable', sa.Boolean(), nullable=True),
    sa.Column('counts_in_position', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('family_code', sa.String(length=40), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('industry', sa.String(length=30), nullable=True),
    sa.Column('business_unit', sa.String(length=60), nullable=True),
    sa.Column('item_type', sa.String(length=20), nullable=True),
    sa.Column('uom', sa.String(length=12), nullable=True),
    sa.Column('pack_size', sa.Float(), nullable=True),
    sa.Column('case_qty', sa.Float(), nullable=True),
    sa.Column('moq', sa.Float(), nullable=True),
    sa.Column('order_multiple', sa.Float(), nullable=True),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.Column('selling_price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('shelf_life_days', sa.Integer(), nullable=True),
    sa.Column('abc_class', sa.String(length=1), nullable=True),
    sa.Column('xyz_class', sa.String(length=1), nullable=True),
    sa.Column('criticality', sa.String(length=10), nullable=True),
    sa.Column('ved', sa.String(length=1), nullable=True),
    sa.Column('sde', sa.String(length=1), nullable=True),
    sa.Column('hazardous', sa.Boolean(), nullable=True),
    sa.Column('temp_requirement', sa.String(length=20), nullable=True),
    sa.Column('country_of_origin', sa.String(length=60), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('volume_m3', sa.Float(), nullable=True),
    sa.Column('lot_tracked', sa.Boolean(), nullable=True),
    sa.Column('serial_tracked', sa.Boolean(), nullable=True),
    sa.Column('target_service_level', sa.Float(), nullable=True),
    sa.Column('lifecycle_status', sa.String(length=12), nullable=True),
    sa.Column('eol_date', sa.Date(), nullable=True),
    sa.Column('revision', sa.String(length=10), nullable=True),
    sa.Column('superseded_by_sku', sa.String(length=60), nullable=True),
    sa.Column('eco_effective_date', sa.Date(), nullable=True),
    sa.Column('eco_reworkable', sa.Boolean(), nullable=True),
    sa.Column('substitute_group', sa.String(length=40), nullable=True),
    sa.Column('markdown_pct', sa.Float(), nullable=True),
    sa.Column('line_stop_cost_per_unit', sa.Float(), nullable=True),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_business_unit'), ['business_unit'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_family_code'), ['family_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_industry'), ['industry'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_sku'), ['sku'], unique=True)

    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.String(length=400), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_table('kpi_definition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('formula', sa.String(length=400), nullable=True),
    sa.Column('unit', sa.String(length=12), nullable=True),
    sa.Column('direction', sa.String(length=12), nullable=True),
    sa.Column('window_days', sa.Integer(), nullable=True),
    sa.Column('entity_level', sa.String(length=12), nullable=True),
    sa.Column('watch', sa.Float(), nullable=True),
    sa.Column('attention', sa.Float(), nullable=True),
    sa.Column('critical', sa.Float(), nullable=True),
    sa.Column('alert_threshold', sa.Float(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('kpi_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=True),
    sa.Column('metric', sa.String(length=40), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('scope', sa.String(length=60), nullable=True),
    sa.Column('source', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kpi_snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kpi_snapshot_as_of'), ['as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_kpi_snapshot_metric'), ['metric'], unique=False)

    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('loc_type', sa.String(length=20), nullable=True),
    sa.Column('echelon', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(length=60), nullable=True),
    sa.Column('country', sa.String(length=60), nullable=True),
    sa.Column('city', sa.String(length=60), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('industry', sa.String(length=30), nullable=True),
    sa.Column('business_unit', sa.String(length=60), nullable=True),
    sa.Column('capacity_units', sa.Float(), nullable=True),
    sa.Column('capacity_m3', sa.Float(), nullable=True),
    sa.Column('is_3pl', sa.Boolean(), nullable=True),
    sa.Column('temp_capable', sa.String(length=40), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_location_industry'), ['industry'], unique=False)
        batch_op.create_index(batch_op.f('ix_location_region'), ['region'], unique=False)

    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=12), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=True),
    sa.Column('detail', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_family',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('replenishment_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope_level', sa.String(length=14), nullable=False),
    sa.Column('scope_key', sa.String(length=120), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('replenishment_policy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_replenishment_policy_scope_level'), ['scope_level'], unique=False)

    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('alert_type', sa.String(length=30), nullable=False),
    sa.Column('scope', sa.String(length=12), nullable=True),
    sa.Column('condition', sa.JSON(), nullable=True),
    sa.Column('severity', sa.JSON(), nullable=True),
    sa.Column('industries', sa.JSON(), nullable=True),
    sa.Column('recommended_action', sa.String(length=60), nullable=True),
    sa.Column('suppress_hours', sa.Integer(), nullable=True),
    sa.Column('escalate_after_hours', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('safety_stock_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope_level', sa.String(length=14), nullable=False),
    sa.Column('scope_key', sa.String(length=120), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('safety_stock_policy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_safety_stock_policy_scope_level'), ['scope_level'], unique=False)

    op.create_table('scenario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_no', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_dataset', sa.String(length=160), nullable=True),
    sa.Column('created_by', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('time_step_days', sa.Integer(), nullable=True),
    sa.Column('horizon_days', sa.Integer(), nullable=True),
    sa.Column('runs', sa.Integer(), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('assumptions', sa.JSON(), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=True),
    sa.Column('is_baseline', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_no')
    )
    op.create_table('setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=60), nullable=True),
    sa.Column('region', sa.String(length=60), nullable=True),
    sa.Column('city', sa.String(length=60), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('industry', sa.String(length=30), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('geo_risk', sa.Float(), nullable=True),
    sa.Column('capacity_units_week', sa.Float(), nullable=True),
    sa.Column('quality_rejection_rate', sa.Float(), nullable=True),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_supplier_industry'), ['industry'], unique=False)

    op.create_table('sync_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.Column('expected_every_hours', sa.Float(), nullable=True),
    sa.Column('records', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source')
    )
    op.create_table('user_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('role', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_no', sa.String(length=20), nullable=True),
    sa.Column('dedupe_key', sa.String(length=200), nullable=True),
    sa.Column('rule_code', sa.String(length=40), nullable=True),
    sa.Column('alert_type', sa.String(length=30), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('occurrences', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('entity_ref', sa.String(length=60), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('root_cause', sa.String(length=255), nullable=True),
    sa.Column('dims', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('impact', sa.JSON(), nullable=True),
    sa.Column('recommended_action', sa.String(length=120), nullable=True),
    sa.Column('owner', sa.String(length=60), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('priority_breakdown', sa.JSON(), nullable=True),
    sa.Column('time_to_impact_days', sa.Float(), nullable=True),
    sa.Column('suppressed', sa.Boolean(), nullable=True),
    sa.Column('suppressed_reason', sa.String(length=160), nullable=True),
    sa.Column('escalated', sa.Boolean(), nullable=True),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_no')
    )
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_alert_type'), ['alert_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_dedupe_key'), ['dedupe_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_rule_code'), ['rule_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('bom_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_item_id', sa.Integer(), nullable=False),
    sa.Column('component_item_id', sa.Integer(), nullable=False),
    sa.Column('qty_per', sa.Float(), nullable=True),
    sa.Column('revision', sa.String(length=10), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('is_alternate', sa.Boolean(), nullable=True),
    sa.Column('alt_group', sa.String(length=40), nullable=True),
    sa.Column('scrap_pct', sa.Float(), nullable=True),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['component_item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['parent_item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bom_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bom_line_component_item_id'), ['component_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bom_line_parent_item_id'), ['parent_item_id'], unique=False)

    op.create_table('calendar_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('event_type', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('demand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('granularity', sa.String(length=1), nullable=True),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('censored', sa.Boolean(), nullable=True),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('demand', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_demand_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_demand_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_demand_period_start'), ['period_start'], unique=False)

    op.create_table('forecast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('granularity', sa.String(length=1), nullable=True),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('forecast_type', sa.String(length=12), nullable=True),
    sa.Column('source', sa.String(length=12), nullable=True),
    sa.Column('p10', sa.Float(), nullable=True),
    sa.Column('p90', sa.Float(), nullable=True),
    sa.Column('version', sa.String(length=40), nullable=True),
    sa.Column('model_name', sa.String(length=60), nullable=True),
    sa.Column('issued_at', sa.Date(), nullable=True),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forecast', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forecast_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forecast_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forecast_period_start'), ['period_start'], unique=False)

    op.create_table('item_location_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('source_location_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('lead_time_days', sa.Float(), nullable=True),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['source_location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item_location_source', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_location_source_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_location_source_location_id'), ['location_id'], unique=False)

    op.create_table('item_supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('lead_time_days', sa.Float(), nullable=True),
    sa.Column('moq', sa.Float(), nullable=True),
    sa.Column('order_multiple', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('capacity_units_week', sa.Float(), nullable=True),
    sa.Column('mode', sa.String(length=12), nullable=True),
    sa.Column('lane', sa.String(length=120), nullable=True),
    sa.Column('origin_port', sa.String(length=60), nullable=True),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item_supplier', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_supplier_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_supplier_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('item_uom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('from_uom', sa.String(length=12), nullable=False),
    sa.Column('to_uom', sa.String(length=12), nullable=False),
    sa.Column('factor', sa.Float(), nullable=False),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item_uom', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_uom_item_id'), ['item_id'], unique=False)

    op.create_table('lead_time_observation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('dest_location_id', sa.Integer(), nullable=True),
    sa.Column('origin', sa.String(length=80), nullable=True),
    sa.Column('lane', sa.String(length=120), nullable=True),
    sa.Column('mode', sa.String(length=12), nullable=True),
    sa.Column('carrier_id', sa.Integer(), nullable=True),
    sa.Column('po_ref', sa.String(length=40), nullable=True),
    sa.Column('ordered_date', sa.Date(), nullable=True),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('lead_time_days', sa.Float(), nullable=False),
    sa.Column('promised_days', sa.Float(), nullable=True),
    sa.Column('qty_ordered', sa.Float(), nullable=True),
    sa.Column('qty_received', sa.Float(), nullable=True),
    sa.Column('rejected_qty', sa.Float(), nullable=True),
    sa.Column('expedited', sa.Boolean(), nullable=True),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carrier.id'], ),
    sa.ForeignKeyConstraint(['dest_location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lead_time_observation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_time_observation_dest_location_id'), ['dest_location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_time_observation_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_time_observation_lane'), ['lane'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_time_observation_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('lot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('lot_no', sa.String(length=60), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('manufacture_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('quality_status', sa.String(length=12), nullable=True),
    sa.Column('country', sa.String(length=60), nullable=True),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'lot_no', name='uq_lot_item_no')
    )
    with op.batch_alter_table('lot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lot_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lot_lot_no'), ['lot_no'], unique=False)

    op.create_table('peg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('supply_type', sa.String(length=10), nullable=True),
    sa.Column('supply_ref', sa.String(length=60), nullable=True),
    sa.Column('demand_type', sa.String(length=8), nullable=True),
    sa.Column('demand_ref', sa.String(length=40), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('demand_date', sa.Date(), nullable=True),
    sa.Column('peg_status', sa.String(length=12), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('peg', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_peg_demand_ref'), ['demand_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_peg_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_peg_location_id'), ['location_id'], unique=False)

    op.create_table('production_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=40), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('qty_completed', sa.Float(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('bom_revision', sa.String(length=10), nullable=True),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('production_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_order_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_order_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_order_order_number'), ['order_number'], unique=True)

    op.create_table('promotion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('family_code', sa.String(length=40), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('uplift_pct', sa.Float(), nullable=True),
    sa.Column('promo_type', sa.String(length=30), nullable=True),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_number', sa.String(length=40), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('dest_location_id', sa.Integer(), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('promised_date', sa.Date(), nullable=True),
    sa.Column('eta_date', sa.Date(), nullable=True),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('expedited', sa.Boolean(), nullable=True),
    sa.Column('mode', sa.String(length=12), nullable=True),
    sa.Column('lane', sa.String(length=120), nullable=True),
    sa.Column('delay_reason', sa.String(length=120), nullable=True),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['dest_location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_order_dest_location_id'), ['dest_location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_order_po_number'), ['po_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_purchase_order_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('return_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Float(), nullable=True),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('reason', sa.String(length=60), nullable=True),
    sa.Column('disposition', sa.String(length=20), nullable=True),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('return_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_return_record_item_id'), ['item_id'], unique=False)

    op.create_table('reusable_asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool_code', sa.String(length=40), nullable=False),
    sa.Column('asset_type', sa.String(length=24), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('owner', sa.String(length=60), nullable=True),
    sa.Column('qty_available', sa.Float(), nullable=True),
    sa.Column('qty_in_transit', sa.Float(), nullable=True),
    sa.Column('qty_repair', sa.Float(), nullable=True),
    sa.Column('qty_lost', sa.Float(), nullable=True),
    sa.Column('unit_value', sa.Float(), nullable=True),
    sa.Column('condition', sa.String(length=12), nullable=True),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reusable_asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reusable_asset_pool_code'), ['pool_code'], unique=False)

    op.create_table('risk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_id', sa.String(length=24), nullable=True),
    sa.Column('risk_type', sa.String(length=30), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('cause', sa.String(length=255), nullable=True),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('impact_value', sa.Float(), nullable=True),
    sa.Column('exposure', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=True),
    sa.Column('recommended_action', sa.String(length=160), nullable=True),
    sa.Column('owner', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('risk_id')
    )
    with op.batch_alter_table('risk', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_risk_type'), ['risk_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('sales_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('so_number', sa.String(length=40), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('ship_from_location_id', sa.Integer(), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('requested_date', sa.Date(), nullable=True),
    sa.Column('promised_date', sa.Date(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['ship_from_location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_order_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_order_ship_from_location_id'), ['ship_from_location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_order_so_number'), ['so_number'], unique=True)

    op.create_table('shipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_no', sa.String(length=40), nullable=False),
    sa.Column('ref_type', sa.String(length=4), nullable=True),
    sa.Column('ref_number', sa.String(length=40), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('carrier_id', sa.Integer(), nullable=True),
    sa.Column('origin_location_id', sa.Integer(), nullable=True),
    sa.Column('dest_location_id', sa.Integer(), nullable=True),
    sa.Column('origin_name', sa.String(length=80), nullable=True),
    sa.Column('mode', sa.String(length=12), nullable=True),
    sa.Column('lane', sa.String(length=120), nullable=True),
    sa.Column('port', sa.String(length=60), nullable=True),
    sa.Column('dispatch_date', sa.Date(), nullable=True),
    sa.Column('promised_date', sa.Date(), nullable=True),
    sa.Column('eta_date', sa.Date(), nullable=True),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('delay_days', sa.Float(), nullable=True),
    sa.Column('delay_reason', sa.String(length=120), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('expedited', sa.Boolean(), nullable=True),
    sa.Column('tracking', sa.String(length=60), nullable=True),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carrier.id'], ),
    sa.ForeignKeyConstraint(['dest_location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['origin_location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipment_dest_location_id'), ['dest_location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipment_lane'), ['lane'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipment_ref_number'), ['ref_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipment_shipment_no'), ['shipment_no'], unique=True)

    op.create_table('allocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('demand_type', sa.String(length=8), nullable=True),
    sa.Column('demand_ref', sa.String(length=40), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('alloc_type', sa.String(length=10), nullable=True),
    sa.Column('policy', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('allocation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_allocation_demand_ref'), ['demand_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_allocation_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_allocation_location_id'), ['location_id'], unique=False)

    op.create_table('inventory_balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('uom', sa.String(length=12), nullable=True),
    sa.Column('last_movement_at', sa.DateTime(), nullable=True),
    sa.Column('last_receipt_at', sa.DateTime(), nullable=True),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lot.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'location_id', 'lot_id', 'state', name='uq_balance')
    )
    with op.batch_alter_table('inventory_balance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_balance_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_balance_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_balance_lot_id'), ['lot_id'], unique=False)

    op.create_table('inventory_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('txn_id', sa.String(length=64), nullable=False),
    sa.Column('txn_type', sa.String(length=24), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('to_location_id', sa.Integer(), nullable=True),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('uom', sa.String(length=12), nullable=True),
    sa.Column('state_from', sa.String(length=20), nullable=True),
    sa.Column('state_to', sa.String(length=20), nullable=True),
    sa.Column('on_hand_before', sa.Float(), nullable=True),
    sa.Column('on_hand_after', sa.Float(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.Column('ref_type', sa.String(length=20), nullable=True),
    sa.Column('ref_id', sa.String(length=60), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('actor', sa.String(length=60), nullable=True),
    sa.Column('reversal_of_id', sa.Integer(), nullable=True),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lot.id'], ),
    sa.ForeignKeyConstraint(['reversal_of_id'], ['inventory_transaction.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.ForeignKeyConstraint(['to_location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('txn_id')
    )
    with op.batch_alter_table('inventory_transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_transaction_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transaction_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transaction_lot_id'), ['lot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transaction_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transaction_ref_id'), ['ref_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transaction_txn_type'), ['txn_type'], unique=False)

    op.create_table('purchase_order_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('qty_ordered', sa.Float(), nullable=False),
    sa.Column('qty_received', sa.Float(), nullable=True),
    sa.Column('qty_in_transit', sa.Float(), nullable=True),
    sa.Column('uom', sa.String(length=12), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('promised_date', sa.Date(), nullable=True),
    sa.Column('eta_date', sa.Date(), nullable=True),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_order_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_order_line_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_order_line_po_id'), ['po_id'], unique=False)

    op.create_table('recommendation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rec_no', sa.String(length=20), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('data_quality', sa.Float(), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alert.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rec_no')
    )
    with op.batch_alter_table('recommendation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendation_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_location_id'), ['location_id'], unique=False)

    op.create_table('sales_order_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('so_id', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('qty_ordered', sa.Float(), nullable=False),
    sa.Column('qty_shipped', sa.Float(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('requested_date', sa.Date(), nullable=True),
    sa.Column('ship_date', sa.Date(), nullable=True),
    sa.Column('delivered_date', sa.Date(), nullable=True),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['so_id'], ['sales_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_order_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_order_line_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_order_line_so_id'), ['so_id'], unique=False)

    op.create_table('serial_number',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('serial_no', sa.String(length=80), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('sold_date', sa.Date(), nullable=True),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lot.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_no')
    )
    with op.batch_alter_table('serial_number', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_serial_number_item_id'), ['item_id'], unique=False)

    op.create_table('transfer_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('to_number', sa.String(length=40), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('from_location_id', sa.Integer(), nullable=True),
    sa.Column('to_location_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('qty_received', sa.Float(), nullable=True),
    sa.Column('ship_date', sa.Date(), nullable=True),
    sa.Column('eta_date', sa.Date(), nullable=True),
    sa.Column('promised_date', sa.Date(), nullable=True),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('mode', sa.String(length=12), nullable=True),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['from_location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lot.id'], ),
    sa.ForeignKeyConstraint(['to_location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transfer_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transfer_order_from_location_id'), ['from_location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfer_order_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfer_order_to_location_id'), ['to_location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfer_order_to_number'), ['to_number'], unique=True)

    op.create_table('action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_no', sa.String(length=20), nullable=True),
    sa.Column('action_type', sa.String(length=30), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('to_location_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Float(), nullable=True),
    sa.Column('need_date', sa.Date(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('why', sa.Text(), nullable=True),
    sa.Column('impact', sa.JSON(), nullable=True),
    sa.Column('risk_level', sa.String(length=10), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=True),
    sa.Column('approval_required', sa.Boolean(), nullable=True),
    sa.Column('approval_reason', sa.String(length=255), nullable=True),
    sa.Column('required_role', sa.String(length=60), nullable=True),
    sa.Column('autonomy', sa.JSON(), nullable=True),
    sa.Column('policy_check', sa.JSON(), nullable=True),
    sa.Column('simulation', sa.JSON(), nullable=True),
    sa.Column('alternatives', sa.JSON(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.Column('recommendation_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alert.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendation.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.ForeignKeyConstraint(['to_location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action_no')
    )
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_status'), ['status'], unique=False)

    op.create_table('shipment_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('po_line_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['po_line_id'], ['purchase_order_line.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipment_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipment_line_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipment_line_shipment_id'), ['shipment_id'], unique=False)

    op.create_table('approval',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('approver', sa.String(length=60), nullable=True),
    sa.Column('role', sa.String(length=60), nullable=True),
    sa.Column('decision', sa.String(length=12), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('modified_payload', sa.JSON(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['action.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_action_id'), ['action_id'], unique=False)

    op.create_table('execution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('connector', sa.String(length=40), nullable=True),
    sa.Column('is_mock', sa.Boolean(), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=True),
    sa.Column('request', sa.JSON(), nullable=True),
    sa.Column('response', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('verification', sa.JSON(), nullable=True),
    sa.Column('external_ref', sa.String(length=60), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['action.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('execution', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_action_id'), ['action_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('execution', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_action_id'))

    op.drop_table('execution')
    with op.batch_alter_table('approval', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_action_id'))

    op.drop_table('approval')
    with op.batch_alter_table('shipment_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipment_line_shipment_id'))
        batch_op.drop_index(batch_op.f('ix_shipment_line_item_id'))

    op.drop_table('shipment_line')
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_status'))
        batch_op.drop_index(batch_op.f('ix_action_item_id'))
        batch_op.drop_index(batch_op.f('ix_action_action_type'))

    op.drop_table('action')
    with op.batch_alter_table('transfer_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transfer_order_to_number'))
        batch_op.drop_index(batch_op.f('ix_transfer_order_to_location_id'))
        batch_op.drop_index(batch_op.f('ix_transfer_order_item_id'))
        batch_op.drop_index(batch_op.f('ix_transfer_order_from_location_id'))

    op.drop_table('transfer_order')
    with op.batch_alter_table('serial_number', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_serial_number_item_id'))

    op.drop_table('serial_number')
    with op.batch_alter_table('sales_order_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_order_line_so_id'))
        batch_op.drop_index(batch_op.f('ix_sales_order_line_item_id'))

    op.drop_table('sales_order_line')
    with op.batch_alter_table('recommendation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendation_location_id'))
        batch_op.drop_index(batch_op.f('ix_recommendation_kind'))
        batch_op.drop_index(batch_op.f('ix_recommendation_item_id'))

    op.drop_table('recommendation')
    with op.batch_alter_table('purchase_order_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_line_po_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_order_line_item_id'))

    op.drop_table('purchase_order_line')
    with op.batch_alter_table('inventory_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_transaction_txn_type'))
        batch_op.drop_index(batch_op.f('ix_inventory_transaction_ref_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_transaction_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_inventory_transaction_lot_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_transaction_location_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_transaction_item_id'))

    op.drop_table('inventory_transaction')
    with op.batch_alter_table('inventory_balance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_balance_lot_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_balance_location_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_balance_item_id'))

    op.drop_table('inventory_balance')
    with op.batch_alter_table('allocation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allocation_location_id'))
        batch_op.drop_index(batch_op.f('ix_allocation_item_id'))
        batch_op.drop_index(batch_op.f('ix_allocation_demand_ref'))

    op.drop_table('allocation')
    with op.batch_alter_table('shipment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipment_shipment_no'))
        batch_op.drop_index(batch_op.f('ix_shipment_ref_number'))
        batch_op.drop_index(batch_op.f('ix_shipment_lane'))
        batch_op.drop_index(batch_op.f('ix_shipment_dest_location_id'))

    op.drop_table('shipment')
    with op.batch_alter_table('sales_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_order_so_number'))
        batch_op.drop_index(batch_op.f('ix_sales_order_ship_from_location_id'))
        batch_op.drop_index(batch_op.f('ix_sales_order_customer_id'))

    op.drop_table('sales_order')
    with op.batch_alter_table('risk', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_risk_risk_type'))
        batch_op.drop_index(batch_op.f('ix_risk_location_id'))
        batch_op.drop_index(batch_op.f('ix_risk_item_id'))

    op.drop_table('risk')
    with op.batch_alter_table('reusable_asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reusable_asset_pool_code'))

    op.drop_table('reusable_asset')
    with op.batch_alter_table('return_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_return_record_item_id'))

    op.drop_table('return_record')
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_order_po_number'))
        batch_op.drop_index(batch_op.f('ix_purchase_order_dest_location_id'))

    op.drop_table('purchase_order')
    op.drop_table('promotion')
    with op.batch_alter_table('production_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_order_order_number'))
        batch_op.drop_index(batch_op.f('ix_production_order_location_id'))
        batch_op.drop_index(batch_op.f('ix_production_order_item_id'))

    op.drop_table('production_order')
    with op.batch_alter_table('peg', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_peg_location_id'))
        batch_op.drop_index(batch_op.f('ix_peg_item_id'))
        batch_op.drop_index(batch_op.f('ix_peg_demand_ref'))

    op.drop_table('peg')
    with op.batch_alter_table('lot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lot_lot_no'))
        batch_op.drop_index(batch_op.f('ix_lot_item_id'))

    op.drop_table('lot')
    with op.batch_alter_table('lead_time_observation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_time_observation_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_lead_time_observation_lane'))
        batch_op.drop_index(batch_op.f('ix_lead_time_observation_item_id'))
        batch_op.drop_index(batch_op.f('ix_lead_time_observation_dest_location_id'))

    op.drop_table('lead_time_observation')
    with op.batch_alter_table('item_uom', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_uom_item_id'))

    op.drop_table('item_uom')
    with op.batch_alter_table('item_supplier', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_supplier_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_item_supplier_item_id'))

    op.drop_table('item_supplier')
    with op.batch_alter_table('item_location_source', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_location_source_location_id'))
        batch_op.drop_index(batch_op.f('ix_item_location_source_item_id'))

    op.drop_table('item_location_source')
    with op.batch_alter_table('forecast', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forecast_period_start'))
        batch_op.drop_index(batch_op.f('ix_forecast_location_id'))
        batch_op.drop_index(batch_op.f('ix_forecast_item_id'))

    op.drop_table('forecast')
    with op.batch_alter_table('demand', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_demand_period_start'))
        batch_op.drop_index(batch_op.f('ix_demand_location_id'))
        batch_op.drop_index(batch_op.f('ix_demand_item_id'))

    op.drop_table('demand')
    op.drop_table('calendar_event')
    with op.batch_alter_table('bom_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bom_line_parent_item_id'))
        batch_op.drop_index(batch_op.f('ix_bom_line_component_item_id'))

    op.drop_table('bom_line')
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_alert_status'))
        batch_op.drop_index(batch_op.f('ix_alert_severity'))
        batch_op.drop_index(batch_op.f('ix_alert_rule_code'))
        batch_op.drop_index(batch_op.f('ix_alert_location_id'))
        batch_op.drop_index(batch_op.f('ix_alert_item_id'))
        batch_op.drop_index(batch_op.f('ix_alert_incident_id'))
        batch_op.drop_index(batch_op.f('ix_alert_dedupe_key'))
        batch_op.drop_index(batch_op.f('ix_alert_alert_type'))

    op.drop_table('alert')
    op.drop_table('user_account')
    op.drop_table('sync_status')
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_industry'))
        batch_op.drop_index(batch_op.f('ix_supplier_code'))

    op.drop_table('supplier')
    op.drop_table('setting')
    op.drop_table('scenario')
    with op.batch_alter_table('safety_stock_policy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_safety_stock_policy_scope_level'))

    op.drop_table('safety_stock_policy')
    op.drop_table('rule')
    op.drop_table('role')
    with op.batch_alter_table('replenishment_policy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_replenishment_policy_scope_level'))

    op.drop_table('replenishment_policy')
    op.drop_table('product_family')
    op.drop_table('notification')
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_region'))
        batch_op.drop_index(batch_op.f('ix_location_industry'))
        batch_op.drop_index(batch_op.f('ix_location_code'))

    op.drop_table('location')
    with op.batch_alter_table('kpi_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kpi_snapshot_metric'))
        batch_op.drop_index(batch_op.f('ix_kpi_snapshot_as_of'))

    op.drop_table('kpi_snapshot')
    op.drop_table('kpi_definition')
    op.drop_table('job')
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_sku'))
        batch_op.drop_index(batch_op.f('ix_item_industry'))
        batch_op.drop_index(batch_op.f('ix_item_family_code'))
        batch_op.drop_index(batch_op.f('ix_item_category'))
        batch_op.drop_index(batch_op.f('ix_item_business_unit'))

    op.drop_table('item')
    op.drop_table('inventory_state_def')
    op.drop_table('industry_profile')
    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_cluster_key'))

    op.drop_table('incident')
    with op.batch_alter_table('external_balance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_balance_system'))

    op.drop_table('external_balance')
    op.drop_table('experiment')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_event_type'))

    op.drop_table('event')
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_region'))
        batch_op.drop_index(batch_op.f('ix_customer_code'))

    op.drop_table('customer')
    with op.batch_alter_table('control_policy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_control_policy_scope_level'))
        batch_op.drop_index(batch_op.f('ix_control_policy_policy_type'))

    op.drop_table('control_policy')
    op.drop_table('carrier')
    op.drop_table('autonomy_rule')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_category'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
